=head1 NAME

B<Media> -- code and scripts for handling electronic media

=head1 DESCRIPTION

The C<Media> project is a workflow for transforming your existing digital
media into new formats (commonly, piles of DVDs into much smaller MPEG-4 video
files suitable for watching on an media centre or a portable device like an
iPad).

=head1 WORKFLOW

There are two scripts you will use almost exclusively to convert your media.

=head2 C<encoder>

When run, the C<encoder> script will wait for encoding jobs to be queued up
(using the C<media> script). It will convert them (using HandBrake) to 
MPEG-4 video files (by default). Once converted, they will be installed
in the right location (see below) and added to your iTunes library.

Run C<perldoc encoder> for more information.

=head2 C<media>

The C<media> script adds new video content to the queue for processing. 
Content such as DVDs, downloaded YouTube videos and any other video files.

Run C<perldoc media> for more information.

=head1 LOCATIONS

The C<Media> project is quite opinionated about how to store and name TV
shows and Movies. If you choose to let it install your media once converted,
it will always create the following structures. The base directories are
changable (see L<Media::Config>), the structures are not.

=head2 Television

With very few exceptions, a TV show has episodes within seasons. Therefore,
within the base location for storing TV, there will be a folder with the
name of the show; inside that will be a folder with the name of the season;
and inside that will be individual files for each episode.

As an example, the first episode of a TV show called "Burn Notice", with the
simple title "Pilot" would be found in:

    /files/tv/Burn Notice/Season 1/01 - Pilot.m4v

=head2 Movies

Movies only have the one feature, but on DVD will often come with extras.
Therefore, within the base location for storing movies, there will be a 
folder with the name, rating and year of the movie; within which are stored
the main feature (also with the name, rating and year of the movie as the 
filename) and any extras. For example, the movie Serenity, stored with the
out-takes would be stored as:

    /files/movies/All/Serenity - 12A (2005)/Serenity - 12A (2005).m4v
    /files/movies/All/Serenity - 12A (2005)/Out-takes.m4v

You will notice an extra "All" directory before the movie. When a movie is
stored, C<Media> will look the movie up in the Internet Movie Database
to determine the genre(s), director(s), writer(s) and major actors appearing
in it. That information is used to create a structure like:

    /files/movies/Director/Joss Whedon/Serenity - 12A (2005).m4v
    /files/movies/Writer/Joss Whedon/Serenity - 12A (2005).m4v
    /files/movies/Genre/Science Fiction/Serenity - 12A (2005).m4v
    /files/movies/Actor/Nathan Fillion/Serenity - 12A (2005).m4v
    
The movie is symbolically linked within these extra directories, so no disk
space is wasted storing multiple copies of the same movie.

=head1 FOLDER NAMES

The C<Media> code determines the details of the video content queued for 
processing in the case of a single video file from the name of the containing
folder, and in the case of a DVD image from the F<dvd.conf> description file
(see L<Media::Handler::DVD> for more details).

=head2 Television

As noted above, television shows mostly have a series, season and episode. 
When processing a single file which represents a single episode, it expects
the directory containing it to be named in a specific format, like so:

    Firefly - 1x01 - Serenity
    Firefly - 1x02 - The Train Job

It is not an error to leave out the episode title. It is not an error to leave
out the season and/or the episode number. 

It is an error to leave out the series name. It is an error to leave out both
the episode number and episode title.

=head2 Movies

Individual files representing a feature or extra from a movie are expected to
be named with the film, rating, year, and in the case of an extra, with the 
title of the extra, like so:

    Serenity - 12A (2005)
    Serenity - 12A (2005) - Outtakes

It is not an error to leave out the rating, it will be taken from the 
information found in the Internet Movie Database. 

It is an error to leave out the year. It is an error to leave out the title of
the movie.

=head1 SEE ALSO

=over

=item

C<perldoc L<Media::Config>> for configuration options

=item

C<perldoc L<Media::Handler::DVD>> for a description of the DVD description
file

=item

C<perldoc L<encoder>> for the list of arguments the F<encoder> script accepts

=item

C<perldoc L<media>> for a description of how the F<media> script works
